export const content = {
  es: {
    nav: { projects: "Proyectos", services: "Servicios", journey: "Trayectoria", recognition: "Reconocimiento", blog: "Blog", contact: "Contacto" },
    hero: {
      eyebrow: "IT Director · AI Solutions Architect",
      titleA: "Treinta años operando TI seria.",
      titleB: "Hoy, construyendo los ",
      titleEm: "agentes",
      titleC: " que la transforman.",
      sub: "Soy Douglas Galindo. Dirijo la tecnología de una universidad de 7,000 usuarios y diseño su capacidad de IA aplicada: sistemas multiagente, machine learning y un data lakehouse moderno. Aplicación práctica de los marcos ITIL · PRINCE2 · ISO 9000, con las manos en el código.",
      ctaProjects: "Ver proyectos",
      ctaBlog: "Leer el blog",
    },
    proof: [
      { num: "30+", label: "años en TI" },
      { num: "7,000", label: "usuarios servidos" },
      { num: "24/7", label: "operación cloud" },
      { num: "4", label: "países liderados" },
    ],
    projects: {
      eyebrow: "Evidencia, no promesas",
      title: "Proyectos de IA e innovación",
      sub: "Cada proyecto lleva su estado real de madurez. Lo que está en producción opera hoy; lo que es prototipo se declara como tal.",
      items: [
        { title: "Pipeline DTE de facturación electrónica", tag: "En producción", tagClass: "tag-prod",
          desc: "Facturación electrónica institucional conforme al mandato DTE de El Salvador. Construido internamente: auditable y sin dependencia de proveedores.",
          stack: "Apache NiFi" },
        { title: "Plataforma de Agentes Hermes", tag: "En desarrollo", tagClass: "tag-dev",
          desc: "Agentes de IA para cada rol de una dirección de TI: agentes especializados, skills reutilizables y memoria auto-mejorable, versionado en GitHub.",
          stack: "Claude · n8n · GitHub" },
        { title: "Data Lakehouse", tag: "Prototipo", tagClass: "tag-proto",
          desc: "Veinte años de datos legados conectados con la analítica y las cargas de IA de hoy, sobre almacenamiento de objetos.",
          stack: "Dremio · Iceberg · Nessie · MinIO/S3" },
        { title: "Asistente docente con IA", tag: "Prototipo", tagClass: "tag-proto",
          desc: "Chat inteligente sobre el contenido de cursos en Moodle — concebido antes de que Google lanzara NotebookLM.",
          stack: "LangChain · Moodle" },
        { title: "ML de retención estudiantil", tag: "Prototipo", tagClass: "tag-proto",
          desc: "Modelo de alerta temprana que identifica estudiantes en riesgo de abandono, para intervenir a tiempo.",
          stack: "KNIME · scikit-learn" },
        { title: "Evaluación de tesis asistida por IA", tag: "Prototipo", tagClass: "tag-proto",
          desc: "Apoyo a jurados con humano en el circuito de decisión, en dos variantes de orquestación.",
          stack: "n8n · CrewAI" },
        { title: "Conscius — compartiendo el conocimiento", tag: "En producción", tagClass: "tag-prod",
          desc: "Programa formativo virtual creado hace 23 años sobre open source — orientó ~$300,000 originalmente destinados a una solución propietaria hacia centros de cómputo, renovación de equipos y capacitaciones.",
          stack: "Moodle · Open source" },
        { title: "CAB2 — Club de Aprendizaje Blended", tag: "Programa", tagClass: "tag-dev",
          desc: "Premisa pionera en educación blended para su época — el cimiento operativo que permitió trasladar toda la operación de los sistemas informáticos a modo remoto durante el COVID-19.",
          stack: "Blended learning · Moodle · Classroom" },
      ],
    },
    services: {
      eyebrow: "Cómo puedo ayudar",
      title: "Consultoría con criterio de arquitecto",
      sub: "Treinta años decidiendo con presupuestos reales. Tecnológicamente agnóstico: gana la mejor opción, sea propietaria u open source.",
      items: [
        { num: "S·01", title: "IA con gobernanza", desc: "Diseño e implementación de capacidades de IA — agentes, ML, automatización — aplicando la disciplina de los marcos ITIL/PRINCE2 y presupuestos realistas. De la idea al sistema operando." },
        { num: "S·02", title: "Costo-beneficio tecnológico", desc: "Evaluación rigurosa de alternativas propietarias vs. open source para decisiones de plataforma: ERP, LMS, BI, infraestructura. Sin ideología: con números." },
        { num: "S·03", title: "Modernización de datos", desc: "Lakehouse, pipelines de integración y analítica de autoservicio que conectan sus datos legados con lo que la organización necesita decidir hoy." },
      ],
    },
    journey: {
      eyebrow: "Trayectoria",
      title: "De RPG/400 a agentes de IA",
      items: [
        { years: "2002 — presente", title: "Director de TI · Universidad Dr. José Matías Delgado",
          desc: "Estrategia, presupuesto y operación 24/7 para 7,000+ usuarios. Transformación ITIL, nube híbrida AWS/OVH y la capacidad de IA aplicada de la institución. Creé \"Conscius — compartiendo el conocimiento\" hace 23 años, orientando ~$300,000 de una solución propietaria a inversiones más sensibles para los usuarios. Creé y operé CAB2 — Club de Aprendizaje Blended, cuya experiencia fue el cimiento para trasladar toda la operación informática a modo remoto durante la pandemia COVID-19." },
        { years: "1996 — 2002", title: "Gerente de Informática · Seguros Universales",
          desc: "Desarrollo e implementación de aplicaciones de bancaseguros e integración financiera, con herramientas actuariales e integración con reaseguradores internacionales. Certificación de TI para fusiones y la migración del año 2000." },
        { years: "1994 — 1996", title: "Director Regional de EDP · Amway Centroamérica",
          desc: "Equipos de TI en tres países, integrados vía satélite con Michigan. Sistemas regionales de inventario, distribución y facturación." },
        { years: "1990 — 1994", title: "Especialista AS/400 · Simán, SOCOMSA",
          desc: "En Simán participé en la conversión de aplicaciones corporativas para la apertura de Simán Guatemala — primera sucursal internacional de Simán Corporación. Equipos de desarrollo RPG/400, sistemas para siete multinacionales y los primeros modelos de metaprogramación para software escalable y auditable." },
      ],
    },
    recognition: {
      eyebrow: "Reconocimiento y voz pública",
      title: "Publicaciones, premios y formación",
      sub: "Conferencias, publicaciones académicas y reconocimientos que documentan el recorrido — y un blog personal paralelo a este sitio.",
      groups: [
        {
          heading: "Publicaciones y reconocimientos",
          items: [
            { title: "Premio Arroba de Oro", body: "Reconocimiento como Webmaster del sitio Comunidad Educativa." },
            { title: "Congreso regional UNESCO", body: "Exposición y publicación de \u201CUso de Herramientas Open Source como una Alternativa Viable y Funcional en el Área Educativa\u201D, desde la experiencia académica desplegando open source en educación superior." },
            { title: "Publicación académica", body: "\u201CHumanware: el elemento clave en todo proyecto de tecnología educativa\u201D — sobre la centralidad de las personas, el cambio y las competencias en iniciativas educativas impulsadas por tecnología." },
            { title: "Untalbudista", body: "Blog personal — \u201Chistorias de un Budista en Latinoamérica\u201D — proyecto de blogging paralelo donde explora reflexión, neurociencia y prácticas contemplativas." },
          ],
        },
        {
          heading: "Formación y eventos",
          items: [
            { title: "Startup Weekend", body: "Silicon Valley (San José, CA). Exposición directa a la metodología lean-startup que inspiró el programa \u201CiMpulso\u201D." },
            { title: "Emprendedurismo Web", body: "Universidad ESAN y Stanford University." },
            { title: "Taller de Desarrollo de Aplicaciones Web", body: "The Pragmatic Programmers, Atlanta." },
          ],
        },
      ],
    },
    blog: {
      eyebrow: "Blog",
      title: "Escribo desde la práctica",
      sub: "Gobernanza de TI, IA aplicada y decisiones de tecnología en entornos donde cada dólar cuenta.",
      all: "Todas las publicaciones",
      back: "← Volver al blog",
      loading: "Cargando publicaciones…",
      empty: "Aún no hay publicaciones. Vuelve pronto.",
      notFound: "Publicación no encontrada.",
    },
    contact: {
      title: "Trabajemos juntos",
      sub: "Disponible para consultoría remota internacional y oportunidades en Berlín, Alemania, Estados Unidos y Centroamérica.",
    },
    footer: { rights: "© 2026 Douglas Galindo · untalDouglas" },
  },

  en: {
    nav: { projects: "Projects", services: "Services", journey: "Journey", recognition: "Recognition", blog: "Blog", contact: "Contact" },
    hero: {
      eyebrow: "IT Director · AI Solutions Architect",
      titleA: "Thirty years running serious IT.",
      titleB: "Now building the ",
      titleEm: "agents",
      titleC: " that transform it.",
      sub: "I'm Douglas Galindo. I run technology for a 7,000-user university and architect its applied-AI capability: multi-agent systems, machine learning, and a modern data lakehouse. Hands-on application of ITIL · PRINCE2 · ISO 9000 frameworks — with hands on the code.",
      ctaProjects: "View projects",
      ctaBlog: "Read the blog",
    },
    proof: [
      { num: "30+", label: "years in IT" },
      { num: "7,000", label: "users served" },
      { num: "24/7", label: "cloud operations" },
      { num: "4", label: "countries led" },
    ],
    projects: {
      eyebrow: "Evidence, not promises",
      title: "AI & innovation projects",
      sub: "Every project carries its real maturity state. What's in production runs today; what's a prototype says so.",
      items: [
        { title: "DTE e-invoicing pipeline", tag: "In production", tagClass: "tag-prod",
          desc: "Institutional electronic invoicing under El Salvador's DTE mandate. Built in-house: auditable, no vendor lock-in.",
          stack: "Apache NiFi" },
        { title: "Hermes Agent Platform", tag: "In development", tagClass: "tag-dev",
          desc: "AI agents for every role of an IT department: specialized agents, reusable skills, and self-improving memory, versioned on GitHub.",
          stack: "Claude · n8n · GitHub" },
        { title: "Data Lakehouse", tag: "Prototype", tagClass: "tag-proto",
          desc: "Twenty years of legacy data connected to today's analytics and AI workloads, on object storage.",
          stack: "Dremio · Iceberg · Nessie · MinIO/S3" },
        { title: "AI teaching assistant", tag: "Prototype", tagClass: "tag-proto",
          desc: "Intelligent chat over Moodle course content — conceived before Google launched NotebookLM.",
          stack: "LangChain · Moodle" },
        { title: "Student retention ML", tag: "Prototype", tagClass: "tag-proto",
          desc: "Early-warning model identifying students at risk of dropping out, enabling timely intervention.",
          stack: "KNIME · scikit-learn" },
        { title: "AI-assisted thesis evaluation", tag: "Prototype", tagClass: "tag-proto",
          desc: "Human-in-the-loop jury support, built in two orchestration variants.",
          stack: "n8n · CrewAI" },
        { title: "Conscius — sharing knowledge", tag: "In production", tagClass: "tag-prod",
          desc: "Virtual learning program built 23 years ago on open source — redirected ~$300K originally earmarked for a proprietary solution to student labs, faculty/staff equipment renewal, and training.",
          stack: "Moodle · Open source" },
        { title: "CAB2 — Blended Learning Club", tag: "Program", tagClass: "tag-dev",
          desc: "Pioneering blended-education program — the operational foundation that enabled the move of all IT services to remote operation during COVID-19.",
          stack: "Blended learning · Moodle · Classroom" },
      ],
    },
    services: {
      eyebrow: "How I can help",
      title: "Consulting with an architect's judgment",
      sub: "Thirty years of decisions on real budgets. Technology-agnostic: the best option wins, proprietary or open source.",
      items: [
        { num: "S·01", title: "AI with governance", desc: "Design and implementation of AI capabilities — agents, ML, automation — applying the discipline of ITIL/PRINCE2 frameworks and realistic budgets. From idea to running system." },
        { num: "S·02", title: "Technology cost-benefit", desc: "Rigorous evaluation of proprietary vs. open source alternatives for platform decisions: ERP, LMS, BI, infrastructure. No ideology — numbers." },
        { num: "S·03", title: "Data modernization", desc: "Lakehouse, integration pipelines, and self-service analytics connecting your legacy data to what the organization needs to decide today." },
      ],
    },
    journey: {
      eyebrow: "Journey",
      title: "From RPG/400 to AI agents",
      items: [
        { years: "2002 — present", title: "IT Director · Universidad Dr. José Matías Delgado",
          desc: "Strategy, budget, and 24/7 operations for 7,000+ users. ITIL transformation, AWS/OVH hybrid cloud, and the institution's applied-AI capability. Created \"Conscius — sharing knowledge\" 23 years ago, redirecting ~$300K from a proprietary solution to higher-impact user investments. Created and operated CAB2 — Blended Learning Club, whose experience became the foundation for moving all IT operations to remote mode during COVID-19." },
        { years: "1996 — 2002", title: "IT Manager · Seguros Universales",
          desc: "Developed and implemented insurance-banking and financial-integration applications, with actuarial tools and international reinsurer integration. IT due-diligence for M&A and the Y2K migration." },
        { years: "1994 — 1996", title: "Regional EDP Director · Amway Central America",
          desc: "IT teams across three countries, satellite-integrated with Michigan. Regional inventory, distribution, and billing systems." },
        { years: "1990 — 1994", title: "AS/400 Specialist · Simán, SOCOMSA",
          desc: "At Simán, participated in the conversion of corporate applications for the opening of Simán Guatemala — Simán Corporation's first international subsidiary. RPG/400 development teams, systems for seven multinationals, and early meta-programming models for scalable, auditable software." },
      ],
    },
    recognition: {
      eyebrow: "Recognition & public voice",
      title: "Publications, awards & development",
      sub: "Conferences, academic publications and recognitions that document the journey — and a personal blog running parallel to this site.",
      groups: [
        {
          heading: "Publications & recognition",
          items: [
            { title: "Arroba de Oro Award", body: "Webmaster recognition for the Comunidad Educativa website." },
            { title: "UNESCO regional congress", body: "Presented and published \u201CUse of Open Source Tools as a Viable and Functional Alternative in the Educational Field,\u201D from the academic experience deploying open source in higher education." },
            { title: "Academic publication", body: "\u201CHumanware: The Key Element in Any Educational Technology Project\u201D — on the centrality of people, change, and skills in technology-driven educational initiatives." },
            { title: "Untalbudista", body: "Personal blog — \u201Cstories of a Buddhist in Latin America\u201D — a parallel writing project exploring reflection, neuroscience, and contemplative practice." },
          ],
        },
        {
          heading: "Development & events",
          items: [
            { title: "Startup Weekend", body: "Silicon Valley (San José, CA). Direct exposure to lean-startup methodology that inspired the \u201CiMpulso\u201D program." },
            { title: "Web Entrepreneurship", body: "Universidad ESAN & Stanford University." },
            { title: "Web Application Development Workshop", body: "The Pragmatic Programmers, Atlanta." },
          ],
        },
      ],
    },
    blog: {
      eyebrow: "Blog",
      title: "Writing from practice",
      sub: "IT governance, applied AI, and technology decisions in places where every dollar counts.",
      all: "All posts",
      back: "← Back to blog",
      loading: "Loading posts…",
      empty: "No posts yet. Come back soon.",
      notFound: "Post not found.",
    },
    contact: {
      title: "Let's work together",
      sub: "Available for international remote consulting and opportunities in Berlin, Germany, the United States, and Central America.",
    },
    footer: { rights: "© 2026 Douglas Galindo · untalDouglas" },
  },
};

export const termLines = [
  [{ t: "hermes ▸ ", c: "agent" }, { t: "boot sequence complete", c: "" }],
  [{ t: "ops ▸ ", c: "agent" }, { t: "17 servers · 2 sites · cloud — ", c: "" }, { t: "all green", c: "ok" }],
  [{ t: "dte-pipeline ▸ ", c: "agent" }, { t: "invoices processed — ", c: "" }, { t: "compliant", c: "ok" }],
  [{ t: "lakehouse·proto ▸ ", c: "agent" }, { t: "iceberg snapshot created · nessie commit", c: "" }],
  [{ t: "retention-ml ▸ ", c: "agent" }, { t: "early-warning scores updated", c: "" }],
  [{ t: "hermes ▸ ", c: "agent" }, { t: "serving 7,000 users since 2002", c: "dim" }],
  [{ t: "hermes ▸ ", c: "agent" }, { t: "status: ", c: "" }, { t: "building what's next", c: "ok" }],
];
